[build]
builder = "nixpacks"
buildCommand = "composer install --no-dev --optimize-autoloader --no-interaction --no-scripts && php bin/console asset-map:compile --env=prod && php bin/console cache:clear --env=prod"

[deploy]
preDeployCommand = "php bin/console doctrine:migrations:migrate --no-interaction --env=prod && php bin/console doctrine:fixtures:load --no-interaction --env=prod"
